import React, { Component } from "react";
import DataService from "../services";
import { Link } from "react-router-dom";
import "../styles/about.css";
export default class About extends Component {
  constructor(props) {
    super(props);
    //this.onChangeSearchTitle = this.onChangeSearchTitle.bind(this);

    this.state = {
    };
  }

  componentDidMount() {
  }

  componentDidUpdate(prevProps) {
    debugger;
    if (this.props.id !== prevProps.id) {
      window.scrollTo(0, 0);
    }
  }

  searchTitle() {
    DataService.findByTitle(this.state.searchTitle)
      .then(response => {
        this.setState({
          tutorials: response.data
        });
        console.log(response.data);
      })
      .catch(e => {
        console.log(e);
      });
  }

  render() {
      return(
        <div className="about-container">
          <div className="about-header">
            What is MoodStreem?
          </div>
          <div className="about-body">
            <div className="about-subheader">
              For Creators
            </div>
            <div className="about-text">
              MoodStreem will be a platform, a marketplace, a workstation, a discussion hub, and much more. We plan to grow 
              enough to encompass the talents of a wide variety of artists, hobbyists, and makers and hope to make it a place where they can 
              develop and thrive. The MoodStreem organization and Streem owners (many of whom are expected to be creators themselves) will be incentivized to 
              promote creations for the benefit of the platform. 
            </div>
            <div className="about-subheader">
              For Viewers
            </div>
            <div className="about-text">
              We want MoodStreem to be a social media platform that changes the landscape. Users will be able to view conveniently
              accessible media in formats similar to the popular modern platforms of today, but with a variety of media and a feature-rich
              comment system worthy of social aggregator apps. All with the added bonus of being able to invest in the content.
              We are beginning with browser support and we plan to develop Android and IOS apps after our initial launch.

            </div>
            <div className="about-subheader">
              For Investors
            </div>
            <div className="about-text">
              MoodStreem will have no shortage of investment opportunities. We are beginning with our OpenSea asset collection which can be accessed through the
              Store page of our site. Eventually the owners of these assets will have access to additional privileges and governance benefits within the ecosystem. We 
              are also planning to release a large, unique themed asset collection prior to the launch of the app. The assets in this collection will provide
              governance benefits to owners as well as acting as avatars on the platform, along with other functions. In addition to these limited edition assets, we
              plan to offer more governance opportunities following our launch. And just as with the content assets generated by our creators, we expect the value of 
              governance assets to generally increase with the success and popularity of the platform. 
            </div>
            <div className="about-subheader">
              For Data Miners
            </div>
            <div className="about-text">
              Data is the life blood for modern social media apps, and this can be both a blessing and a curse, especially when it comes to the privacy of users. MoodStreem
              is dedicated to avoiding the collection of and protecting personally identifying data of its users, but we will certainly not be ignoring the valuable insights 
              that will emerge from the activity on our platform. Media sharing, trading, and page actions will be at the core of our logging initially, but we plan to introduce
              unique and unifying features that we believe will produce novel data in the realms of both social media and digital assets. While we will work towards collecting
              this data in ways that are beneficial to the success of the ecosystem, we also just think it will be really neat to see!
            </div>
            <div className="about-subheader">
              At Its Essense
            </div>
            <div className="about-text">
            What is the value of viral media? An image, video, song, joke, or just 144 characters or less that perfectly relate to a feeling that you will never forget - that becomes popular enough to result in a tidal wave of copies, homages, mockeries, mentions and, of course, clicks. Think of one of your favorites of the century so far. It's probably something that millions of people experienced and related to all at once and over and over again for years as it melded into the zeitgeist. If you could own a piece of its creation, a piece that was generated at its birth and possibly made by the creator themselves; A piece that proves it happened and tells the world how much it means to you, or even, that you were there - What would that be worth to you? What would it be worth to someone who feels as strongly or even more so about the content? What will it be worth if it stands the test of time for a few more decades and kids who weren't even around when it was made start to wonder where it came from?
            <br/><br/>
            At MoodStreem, we think it's worth a lot, and we think that the value will increase as the world continues to recognize that these digital moments in time, these memetic milestones of our social history, can be be owned and traded like any other asset. 
            <br/><br/>
            At the heart of MoodStreem is the idea that every content creator owns the essense of their creation - Your memes belong to you. As long as a user's media is not found to contain trademarked or copyrighted content(or content that has otherwise been deemed unfair to use by the community), the MoodStreem platform will allow the sale of non-fungible assets representing ownership and commemoration of its creation. 
            <br/><br/>
            But MoodStreem doesn't stop at allowing content creators to own the essense of their work. Content on MoodStreem will be divided into categories, or Streems, that will be created, managed, and owned by users of the platform. Creation of a Streem will be guided by the approval of the community but the owner of the Streem will have the power to set and update visual and promotion settings or sell the Streem to another user, and will receive a portion of royalties from content sales that happen within the Streem as long as they are the owner. This means that the Streems will act as digital real estate. Streem owners will be incentivized to enhance the environment of their Streems and promote interesting content. 
            <br/><br/>
            What we are trying to create is a self-managed ecosystem of creators, viewers, investors, and administrators. What we initially build it into is not going to be its final state. It will continue to develop and adapt along with its community for as long as it exists. We don't expect this to be easy, but we are a dedicated team. If the concept interests you, we welcome you to contribute to its development or help support the project in any way you are able. We have a great deal of growth ahead of us and we hope you will join us in seeing what MoodStreem becomes!
            </div>
          </div>

        </div>
      );
  }
}